local tbl = 
{
	
	{
		id = 0,
		name = "Empty Block",
		name2 = "<<< Node Level Under 70 >>>",
	},
	
	{
		addchain = "1",
		ephemeral = true,
		id = 20,
		legend = true,
		name = "Single Mind",
		name2 = "SM under 70 1",
		nodelvllt = 69,
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 12,
		legend = true,
		name = "Impulsive Appraisal II",
		name2 = "IA II under 70 1",
		nodelvllt = 69,
		normal = true,
		reqchain = "1",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 20,
		legend = true,
		name = "Single Mind",
		name2 = "SM under 70 2",
		nodelvllt = 69,
		normal = true,
		reqchain = "1",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 12,
		legend = true,
		name = "Impulsive Appraisal II",
		name2 = "IA II under 70 2",
		nodelvllt = 69,
		normal = true,
		reqchain = "1",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 20,
		legend = true,
		name = "Single Mind",
		name2 = "SM under 70 3",
		nodelvllt = 69,
		normal = true,
		reqchain = "1",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 13,
		legend = true,
		name = "Methodical Appraisal",
		name2 = "MA under 70 last",
		nodelvllt = 69,
		normal = true,
		reqchain = "1",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 23,
		lastskill = true,
		legend = true,
		name = "Stickler",
		name2 = "Stickler - under 70 no enough rare",
		nodelvllt = 69,
		normal = true,
		rarelt = 450,
		reqchain = "1",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		id = 0,
		name = "Empty Block",
		name2 = "<<< gp 600 - 800 >>>",
	},
	
	{
		ephemeral = true,
		gpgt = 799,
		id = 20,
		legend = true,
		name = "Single Mind",
		name2 = "800gp Single Mind",
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 12,
		legend = true,
		name = "Impulsive Appraisal II",
		name2 = "<add-cm4>IA II - under 600gp 1",
		normal = true,
		singlecheck = true,
		singleuse = true,
		startgplt = 599,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 23,
		legend = true,
		name = "Stickler",
		name2 = "<cm4>Stickler - under 600",
		normal = true,
		reqchain = "4",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 12,
		legend = true,
		name = "Impulsive Appraisal II",
		name2 = "<cm4>IA II under 600 2",
		normal = true,
		reqchain = "4",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 13,
		lastskill = true,
		legend = true,
		name = "Methodical Appraisal",
		name2 = "<cm4> MA last hit",
		normal = true,
		reqchain = "4",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 12,
		legend = true,
		name = "Impulsive Appraisal II",
		name2 = "Impulsive Appraisal II - 1",
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 20,
		legend = true,
		name = "Single Mind",
		name2 = "Single Mind - 1",
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 12,
		legend = true,
		name = "Impulsive Appraisal II",
		name2 = "Impulsive Appraisal II - 2",
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 20,
		legend = true,
		name = "Single Mind",
		name2 = "Single Mind - 2",
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		addchain = "1",
		ephemeral = true,
		eyeproc1 = true,
		eyeproc2 = true,
		id = 13,
		legend = true,
		name = "Methodical Appraisal",
		name2 = "<add-cm1> Methodical Appraisal",
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
		weyes = true,
	},
	
	{
		ephemeral = true,
		id = 20,
		legend = true,
		name = "Single Mind",
		name2 = "<cm1>Single Mind",
		normal = true,
		reqchain = "1",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 23,
		lastskill = true,
		legend = true,
		name = "Stickler",
		name2 = "<cm1>Stickler - last hit",
		normal = true,
		reqchain = "1",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		addchain = "2",
		chainNot = "1",
		ephemeral = true,
		eyeproc1 = true,
		id = 13,
		legend = true,
		name = "Methodical Appraisal",
		name2 = "<add-cm2-1steye>Methodical Appraisal",
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
		weyes = true,
	},
	
	{
		addchain = "2",
		chainNot = "1",
		ephemeral = true,
		eyeproc2 = true,
		id = 13,
		legend = true,
		name = "Methodical Appraisal",
		name2 = "<add-cm2-2deye>Methodical Appraisal",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
		weyes = true,
	},
	
	{
		ephemeral = true,
		id = 17,
		legend = true,
		name = "Utmost Caution",
		name2 = "<cm2>Utmost Caution",
		normal = true,
		reqchain = "2",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 13,
		lastskill = true,
		legend = true,
		name = "Methodical Appraisal",
		name2 = "<cm2>MA - last hit",
		normal = true,
		reqchain = "2",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		chainNot = "1,2",
		ephemeral = true,
		id = 12,
		legend = true,
		name = "Impulsive Appraisal II",
		name2 = "IA-II noeye 1st and 2d",
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
		weyes = true,
	},
	
	{
		chainNot = "1,2",
		ephemeral = true,
		id = 17,
		legend = true,
		name = "Utmost Caution",
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		chainNot = "1,2",
		ephemeral = true,
		eyeproc3 = true,
		id = 13,
		legend = true,
		name = "Methodical Appraisal",
		name2 = "MA 3rd eye or zero",
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		chainNot = "1,2",
		ephemeral = true,
		id = 23,
		lastskill = true,
		legend = true,
		name = "Stickler",
		name2 = "Stickler - zero eye",
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
		weyes = true,
	},
	
	{
		ephemeral = true,
		g_skfunc = "--- g_skfunc(itemid, buffDB ,normal_data , collect_data , node_data)\n--- d(itemid) , d(buffDB) , d(normal_data)-- normal gather widowdata , d(collect_data)-- collectable windowdata  ;then you can get datainside from console\n--- d(node_data) -- node specific recorded data\nif table.valid(collect_data) then\n    ---value from collectable_window\n    local chance = collect_data.chance\n    local rarity = collect_data.rarity\n    local attempt = collect_data.attempt\n    local scour_gain = collect_data.scour_gain\n    local brazen_gain = collect_data.brazen_gain\n    local meticulous_gain = collect_data.meticulous_gain\n    local meticulous_chance = collect_data.meticulous_chance\n    local intuition_percentage = collect_data.intuition_percentage\n    local job = Player.job\n\n    local scrutiny_gain = Settings.MadaoGather.GMP[itemid].scrutiny or 200 -- get recorded scrutiny gain value\n\n    ---collect skill ids\n    local scour_id = job == 16 and 22182 or 22186\n    local brazen_id = job == 16 and 22183 or 22187\n    local meti_id = job == 16 and 22184 or 22188\n    local scrutiny_id = job == 16 and 22185 or 22189\n    local wise_id = job == 16 and 26521 or 26522\n    local solid_id = job == 16 and 232 or 215\n    --  d(ActionList:Get(1, 26521):IsReady())\n    local gp_current = Player.gp.current\n    if rarity == 1000 and Player.level >= 90 then\n        local wise = ActionList:Get(1, wise_id)\n        if table.valid(wise) and wise:IsReady() then\n            return wise_id\n        end\n        if gp_current >= 300 then\n            return solid_id\n        end\n    end\n    if attempt > 1 then\n        ---finish up\n        if rarity + meticulous_gain >= 1000 then\n            return meti_id\n        elseif rarity + scour_gain >= 1000 then\n            return scour_id\n        end\n\n        ---Scrutiny check\n        if not buffDB[757] then\n            if gp_current >= 200 then\n                if rarity + meticulous_gain + scrutiny_gain >= 1000 then\n                    return scrutiny_id\n                elseif rarity + scour_gain + scrutiny_gain >= 1000 then\n                    return scrutiny_id\n                end\n            end\n        end\n        if node_data.startgp >= 400 then\n            if not buffDB[757] and gp_current >= 200 then\n                return scrutiny_id\n            end\n            return meti_id\n        else\n            --spam brazen if lack of start gp\n            return brazen_id\n        end\n    end\nend",
		id = -2,
		legend = true,
		name = "Assign Skill From Script",
		name2 = "5.4 collectable skill function",
		normal = true,
		singlecheck = false,
		singleuse = false,
		unspoil = true,
	},
}



return tbl